spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/upload?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

      #jdbc:mysql://localhost:3306/upload?serverTimezone=GMT%2B8&useSSL=false

#页面访问配置
 # mvc:
  #  view:
    #  prefix: /webapp/
     # suffix: .html


  #spring boot 文件上传配置
  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 10Mb
        max-request-size: 100Mb


#mybatis-plus路径配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.soyuan.uploadimg.pojo
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false



  #mybatis:
  # type-aliases-package: com.soyuan.uploadimg.pojo
  # mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  #config-location: classpath:mybatis/mybatis-config.xml